# Generated by Django 5.2.1 on 2025-05-20 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='flights',
            new_name='flight',
        ),
    ]
