# Generated by Django 5.2.1 on 2025-05-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_rename_flights_booking_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
